<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%-- <%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%> --%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Reports List</title>

<jsp:include page="../Admin/AdminCSS.jsp"></jsp:include>
</head>
<body>

	<!-- Header -->
	<jsp:include page="../Admin/AdminHeader.jsp"></jsp:include>

	<div class="container-fluid page-body-wrapper">
		<!-- Sidebar -->
		<jsp:include page="../Admin/AdminLeftSidebar.jsp"></jsp:include>

		<!-- Main Content -->
		<div class="main-panel">
			<div class="content-wrapper">
				<h2 class="text-dark font-weight-bold mb-2">Generated Reports</h2>

				<div class="d-flex justify-content-between align-items-center mb-3">
					<h3 class="mb-0">Generated Reports</h3>
					<a href="generateReport" class="btn btn-primary btn-sm"> <i
						class="mdi mdi-plus-circle-outline"></i>
						Generate Report </a>
				</div>

				<div class="card shadow-sm">
					<div class="card-body table-responsive">

						<table class="table table-bordered table-hover align-middle">
							<thead class="table-dark text-center">
								<tr>
									<th>Report Type</th>
									<th>Generated By</th>
									<th>Generated Date</th>
									<th>Report Summary</th>
									<th>Actions</th>
								</tr>
							</thead>

							<tbody>

								<c:if test="${empty reports}">
									<tr>
										<td colspan="5" class="text-center text-muted">No Reports
											Found.</td>
									</tr>
								</c:if>

								<c:forEach items="${reports}" var="report">
									<tr>

										<!-- Report Type Badge -->
										<td class="text-center"><c:choose>
												<c:when test="${report.reportType == 'PROJECT'}">
													<span class="badge bg-primary">Project</span>
												</c:when>
												<c:when test="${report.reportType == 'PRODUCTIVITY'}">
													<span class="badge bg-success">Productivity</span>
												</c:when>
												<c:otherwise>
													<span class="badge bg-warning text-dark">Billing</span>
												</c:otherwise>
											</c:choose></td>

										<!-- Generated By -->
										<td class="text-center">${report.generatedByName}<!-- You can map user name in DTO -->
										</td>

										<!-- Generated Date -->
										<td class="text-center"><fmt:formatDate
												value="${report.generatedDate}" pattern="dd-MM-yyyy HH:mm" />
										</td>

										<!-- Report Data (Short Preview) -->
										<%--<td><c:choose>
												 <c:when test="${fn:length(report.reportData) > 100}">
                                        ${fn:substring(report.reportData, 0, 100)}...
                                    </c:when>
												<c:otherwise>
                                        ${report.reportData}
                                    </c:otherwise>
											</c:choose></td>--%>

										<!-- Actions -->
										<td class="text-center"><a
											href="viewReport?reportId=${report.reportId}" class="btn btn-sm btn-info">
												<i class="mdi mdi-eye"></i>View
										</a> <a href="editReport?reportId=${report.reportId}"
											class="btn btn-sm btn-warning"> <i class="mdi mdi-pencil"></i>
												Edit
										</a><a href="deleteReport?reportId=${report.reportId}"
											class="btn btn-sm btn-danger"
											onclick="return confirm('Are you sure you want to delete this report?')">
												<i class="mdi mdi-delete"></i>Delete
										</a></td>

									</tr>
								</c:forEach>

							</tbody>

						</table>

					</div>
				</div>
			</div>
			<!-- partial:partials/_footer.html -->
			<jsp:include page="../Admin/AdminFooter.jsp"></jsp:include>
		</div>
		<!-- main-panel ends -->
	</div>
	<!-- page-body-wrapper ends -->

</body>
</html>
