<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Reports List</title>

<jsp:include page="../../GlobalCSS.jsp"></jsp:include>
</head>
<body>

	<!-- Header -->
	<jsp:include page="../includes/AdminHeader.jsp"></jsp:include>

	<div class="container-fluid page-body-wrapper">
		<!-- Sidebar -->
		<jsp:include page="../includes/AdminLeftSidebar.jsp"></jsp:include>

		<!-- Main Content -->
		<div class="main-panel">
			<div class="content-wrapper">
				<h2 class="text-dark font-weight-bold mb-2">Generated Reports</h2>

				<div class="d-flex justify-content-between align-items-center mb-3">
					<h3 class="mb-0 text-dark-emphasis">Generated Reports</h3>
					<a href="generateReport" class="btn btn-primary btn-sm"> <i
						class="mdi mdi-plus-circle-outline"></i> Generate Report
					</a>
				</div>

				<div class="card shadow-sm">
					<div class="card-body table-responsive">

						<table class="table table-bordered table-hover align-middle">
							<thead class="table-dark text-center">
								<tr>
									<th>#</th>
									<th>Title</th>
									<th>Type</th>
									<th>Status</th>
									<th>Hours</th>
									<th>Tasks</th>
									<th>Productivity</th>
									<th>Download</th>
								</tr>
							</thead>

							<tbody>

								<c:if test="${empty reports}">
									<tr>
										<td colspan="5" class="text-center text-dark-emphasis">No
											Reports Found.</td>
									</tr>
								</c:if>

								<c:forEach items="${reports}" var="r" varStatus="i">
									<tr>
										<td class="text-dark-emphasis">${i.count}</td>

										<!-- Generated By -->
										<td class="text-center text-dark-emphasis">${r.reportTitle}
										</td>

										<!-- Report Type Badge -->
										<td class="text-center"><c:choose>
												<c:when test="${r.reportType == 'PROJECT'}">
													<span class="badge bg-primary">PROJECT</span>
												</c:when>
												<c:otherwise>
													<span class="badge bg-primary">PRODUCTIVITY</span>
												</c:otherwise>
											</c:choose></td>

										<!-- Generated Date -->
										<td class="text-center text-dark-emphasis"><c:choose>
												<c:when test="${r.reportStatus == 'PROCESSING'}">
													<span class="badge bg-warning">PROCESSING</span>
												</c:when>
												<c:when test="${r.reportStatus == 'COMPLETED'}">
													<span class="badge bg-success">COMPLETED</span>
												</c:when>
												<c:otherwise>
													<span class="badge bg-danger">FAILED</span>
												</c:otherwise>
											</c:choose></td>

										<!-- Total Hours -->
										<td class="text-dark-emphasis">${r.totalHours}</td>

										<td class="text-dark-emphasis">${r.totalTasks}</td>

										<td class="text-dark-emphasis">${r.productivityScore}%</td>

										<!-- Actions -->
										<td class="text-center"><%-- <a
											href="viewReportAnalysis?reportId=${r.reportId}"
											class="btn btn-sm btn-primary">View</a> --%> <a
											href="downloadReport?reportId=${r.reportId}"
											class="btn btn-sm btn-success">Download</a></td>

									</tr>
								</c:forEach>

							</tbody>

						</table>

						<!-- 🔹 Charts Section -->
						<div class="row mt-5">

							<div class="col-md-12">
								<div class="card p-3">
									<canvas id="reportChart"></canvas>
								</div>
							</div>

						</div>


					</div>
				</div>
			</div>
			<!-- partial:partials/_footer.html -->
			<jsp:include page="../../GlobalFooter.jsp"></jsp:include>
		</div>
		<!-- main-panel ends -->
	</div>
	<!-- page-body-wrapper ends -->

	<!-- Chart js -->
	<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
	<script>
		let reports = JSON.parse('${reportsJson}');

		console.log("Reports:", reports);

		if (reports && reports.length > 0 && reports[0].chartData) {

			let chartData = JSON.parse(reports[0].chartData);

			console.log("Chart Data:", chartData);

			const canvas = document.getElementById('reportChart');

			if (canvas) {
				new Chart(canvas, {
					type : 'line',
					data : {
						labels : chartData.labels || [],
						datasets : [ {
							label : 'Hours per Day',
							data : chartData.data || [],
							borderWidth : 2,
							tension : 0.3
						} ]
					}
				});
			}

		} else {
			console.warn("No chart data available");
		}
	</script>

</body>
</html>
