<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Report Details</title>
<jsp:include page="../../GlobalCSS.jsp"></jsp:include>

<!-- Chart.js -->
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>
<body>

	<!-- Header -->
	<jsp:include page="../includes/AdminHeader.jsp"></jsp:include>

	<div class="container-fluid page-body-wrapper">

		<!-- Sidebar --> 
		<jsp:include page="../includes/AdminLeftSidebar.jsp"></jsp:include>

		<!-- Main Content -->
		<div class="main-panel">
			<div class="content-wrapper">

				<h2 class="text-dark font-weight-bold mb-2">Report Details</h2>

				<div class="d-flex justify-content-between align-items-center mb-3">
					<h3 class="mb-0 text-dark-emphasis">Report Details</h3>
					<a href="listReports" class="btn btn-secondary btn-sm">Back to
						List</a>
				</div>

				<div class="card shadow-sm">
					<div class="card-body">

						<table class="table table-borderless">

							<tr>
								<th width="30%">Report Title</th>
								<td>${report.reportTitle}</td>
							</tr>

							<tr>
								<th>Report Type</th>
								<td><c:choose>
										<c:when test="${report.reportType == 'PROJECT'}">
											<span class="badge bg-primary">PROJECT</span>
										</c:when>
										<c:otherwise>
											<span class="badge bg-info text-dark">PRODUCTIVITY</span>
										</c:otherwise>
									</c:choose></td>
							</tr>

							<tr>
								<th>Generated By</th>
								<td>${report.generatedBy.firstName}
									${report.generatedBy.lastName}</td>
							</tr>

							<tr>
								<th>Project</th>
								<td>${report.project.projectName}</td>
							</tr>

							<tr>
								<th>Date Range</th>
								<td>${report.fromDate}→${report.toDate}</td>
							</tr>

							<tr>
								<th>Status</th>
								<td><c:choose>
										<c:when test="${report.reportStatus == 'PROCESSING'}">
											<span class="badge bg-warning">PROCESSING</span>
										</c:when>
										<c:when test="${report.reportStatus == 'COMPLETED'}">
											<span class="badge bg-success">COMPLETED</span>
										</c:when>
										<c:otherwise>
											<span class="badge bg-danger">FAILED</span>
										</c:otherwise>
									</c:choose></td>
							</tr>

							<tr>
								<th>Total Hours</th>
								<td><strong>${report.totalHours} hrs</strong></td>
							</tr>

							<tr>
								<th>Total Tasks</th>
								<td>${report.totalTasks}</td>
							</tr>

							<tr>
								<th>Completed Tasks</th>
								<td><span class="text-success">${report.completedTasks}</span></td>
							</tr>

							<tr>
								<th>Pending Tasks</th>
								<td><span class="text-warning">${report.pendingTasks}</span></td>
							</tr>

							<tr>
								<th>Productivity Score</th>
								<td>
									<div class="progress">
										<div class="progress-bar bg-success"
											style="width: ${report.productivityScore}%;">
											${report.productivityScore}%</div>
									</div>
								</td>
							</tr>

							<tr>
								<th>Download Report</th>
								<td><c:if test="${not empty report.filePath}">
										<a href="${report.filePath}" class="btn btn-sm btn-primary">
											Download File </a>
									</c:if> <c:if test="${empty report.filePath}">
										<span class="text-muted">Not Available</span>
									</c:if></td>
							</tr>

							<tr>
								<th>Created At</th>
								<td>${report.createdAt}</td>
							</tr>

							<tr>
								<th>Updated At</th>
								<td>${report.updatedAt}</td>
							</tr>

						</table>

						<!-- Chart Section -->
						<div class="card shadow-sm mt-4">
							<div class="card-header bg-dark text-white">
								<h5 class="mb-0">Report Chart</h5>
							</div>
							<div class="card-body text-center">
								<c:choose>
									<c:when test="${not empty report.chartData}">
										<%-- chartData is Base64 PNG — render directly, no JS needed --%>
										<img src="data:image/png;base64,${report.chartData}"
											alt="Report Chart" class="img-fluid"
											style="max-width: 700px;" />
									</c:when>
									<c:otherwise>
										<p class="text-muted">No chart available for this report.</p>
									</c:otherwise>
								</c:choose>
							</div>
						</div>

					</div>
				</div>

			</div>

			<jsp:include page="../../GlobalFooter.jsp"></jsp:include>
		</div>
	</div>

</body>
</html>